BackToVillage/ViewModels/EditProfile.cs
using BackToVillage.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BackToVillage.ViewModels
{
    public class EditProfile
    {
        public int UserId { get; set; }

        [Display(Name = "Name")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Please enter your first name.")]
        [Display(Name = "First Name")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "The First Name must be less than 50 characters.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter your last name.")]
        [StringLength(50, ErrorMessage = "The Last Name must be less than 50 characters.")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter an email address.")]
        [EmailAddress(ErrorMessage = "The Email Address is not valid.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter your Date of Birth.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DOB { get; set; }

        public int? Age { get; set; }

        [Required(ErrorMessage = "Please enter your Phone number.")]
        [Display(Name = "Phone No.")]
        [StringLength(10)]
        public string PhoneNumber { get; set; }

        [Display(Name = "Alternate Phone No. ")]
        [StringLength(10)]
        public string AltPhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter your address.")]
        public string Address { get; set; }

        public int? CityId { get; set; }

        [Display(Name = "City")]
        public string CityName { get; set; }

        [Display(Name = "City")]
        public List<City> CityList { get; set; }

        [Required(ErrorMessage = "Please select a city.")]
        public int? SelectedCityId { get; set; }

        public int? StateId { get; set; }

        [Display(Name = "State")]
        public string StateName { get; set; }

        [Display(Name = "State")]
        public List<State> StateList { get; set; }

        [Required(ErrorMessage = "Please select a state.")]
        public int? SelectedStateId { get; set; }

        public int? OccupationId { get; set; }

        [Display(Name = "Occupation")]
        public string OccupationName { get; set;}

        [Display(Name = "Occupation")]
        public List<Occupation> OccupationList { get; set; }

        [Required(ErrorMessage = "Please select your Occupation.")]
        public int? SelectedOccupationId { get; set; }

        public string ImageFileName { get; set; }
        public string ImagePath { get; set; }

        public string Role { get; set; }
        public int? roleId { get; set; }
        
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string HashPassword { get; set; }
        
        [CompareAttribute("Password", ErrorMessage = "This Password is not same as the above.")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        public string ConfirmPassword { get; set; }
    }
}

BackToVillage/Controllers/UserAccountController.cs
/***********************************************************************************
 *                                                                                 *
 *    File Name:   UserAccountController                                           *
 *                                                                                 *
 *    Created On:  08/08/2016                                                      *
 *                                                                                 *
 *    Description: This file defines the methods that perform the basic            *
 *                 required functionalities related to an user's account like      *                 
 *                 Register, Log In, Edit Profile, Change Password and             * 
 *                 Delete Account.                                                 *
 *                                                                                 *
 ***********************************************************************************/

using BackToVillage.BusinessLayer;
using BackToVillage.Filters;
using BackToVillage.Utilities;
using BackToVillage.ViewModels;
using System;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BackToVillage.Controllers
{
    public class UserAccountController : Controller
    {
        AccountBl userAccount = new AccountBl();

        // GET: UserProfile
        public ActionResult Register()
        {
            var user = userAccount.GetLists();
            return View(user);
        }

        /// <summary>
        /// Registers Users
        /// </summary>
        /// <param name="userObject"></param>
        /// <returns> Register View</returns>
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(UserDetails userObject)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!userAccount.CheckEmail(userObject.Email))
                    {
                       bool status =  userAccount.AddUser(userObject);
                       ViewBag.Message = status? BTV_Constants.RegistrationSuccess: BTV_Constants.RegistrationFailure;
                       
                    }
                    else
                    {
                        ViewBag.Message = BTV_Constants.EmailExists;
                    }

                    ModelState.Clear();
                }
                
            }
            catch (Exception ex)
            {
                // If we got this far, something failed, redisplay form
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                ModelState.AddModelError("Error", BTV_Constants.ModelError);
            }
            
            var lists = userAccount.GetLists();
            return View(lists);
        }

        //GET: Login
        public ActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// User Login 
        /// </summary>
        /// <param name="user"></param>
        /// <returns>Profile View Based on Role</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginVm user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string password = user.Password;
                    user.HashPassword = password.GetHashCode().ToString();
                    var result = userAccount.UserLogin(user);

                    if (result)
                    {
                        var userId = new AccountBl().GetUserId(user.Email);
                        var roleId = userAccount.GetRole(userId);
                        Session["user"] = userId;

                        switch (roleId)
                        {
                            case (int)UserRoles.Admin:
                                return RedirectToAction("AdminProfile", "Admin");

                            case (int)UserRoles.GroupMember:
                                return RedirectToAction("UserProfile", "User");

                            case (int)UserRoles.User:
                                return RedirectToAction("UserProfile", "User");

                            default:
                                return View();
                        }
                    }
                    ViewBag.Message = BTV_Constants.LoginFail;
                }
            }

            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                ModelState.AddModelError("Error", BTV_Constants.ModelError);
            }
            return View();
        }

        /// <summary>
        /// Bind Cities according to State selection
        /// </summary>
        /// <param name="stateId"></param>
        /// <returns>City List according to State selection</returns>
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult LoadCitiesByState(int stateId)
        {
            try
            {
                if (stateId > 0)
                {
                    var city = new AccountBl();

                    var cityList = city.GetCities(Convert.ToInt32(stateId));
                    var cityData = cityList.Select(m => new SelectListItem()
                    {
                        Text = m.CityName,
                        Value = m.CityId.ToString(),
                    });
                    return Json(cityData, JsonRequestBehavior.AllowGet);
                }

                ModelState.AddModelError("Error", BTV_Constants.ModelError);

            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                ModelState.AddModelError("Error", BTV_Constants.ModelError);
            }
            return null;
        }

        [AuthenticateUser]
        public ActionResult LogOut()
        {
            Session.Clear();
            Session.Abandon();
            return RedirectToAction("Index", "Home");

        }

        /// <summary>
        /// To perform Photo Upload
        /// </summary>
        /// <param name="imageData"></param>
        /// <returns></returns>
        [HttpPost]
        public string UploadPhoto(HttpPostedFileBase imageData)
        {
            try
            {
                var photoPath = ConfigurationManager.AppSettings["ProfilePhotoPath"];

                if (imageData != null && imageData.ContentLength > 0)
                {
                    AccountBl user = new AccountBl();

                    // extract the fielname
                    var fileName = Path.GetFileName(imageData.FileName);

                    if (!String.IsNullOrEmpty(fileName))
                    {
                        // store the file in a separate folder
                        var path = Path.Combine(photoPath, fileName);
                        var uid = (int)Session["user"];
                        imageData.SaveAs(path);
                        user.SavePhotoPath(path, uid);
                        string profilePhotoPath = userAccount.GetProfilePhoto(path);
                        ViewBag.ImageUrl = profilePhotoPath;
                        ViewBag.ImageUrl = userAccount.GetProfilePhoto(path);
                        return profilePhotoPath;
                    }

                }
            }

            catch (Exception ex)
            {
                ViewBag.Message = BTV_Constants.PhotoUploadError;
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
            }

            return String.Empty;

        }

        /// <summary>
        /// Edit Profile
        /// </summary>
        [AcceptVerbs(HttpVerbs.Get)]
        [AuthenticateUser]
        public ActionResult Edit()
        {
            var userId = (int)Session["user"];
            EditProfile userDetails = userAccount.GetuserDetailsAndLists(userId);
           // if (userDetails.roleId == (int) UserRoles.Admin)
            //{
                return View(userDetails);
            //}

           // return PartialView("_EditProfile",userDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditProfile user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!userAccount.CheckEmail(user.Email))
                    {
                        user.UserId = (int)Session["user"];
                        userAccount.EditUser(user);
                        ViewBag.Message = BTV_Constants.EditProfileSuccess;
                    }

                    else
                    {
                        ViewBag.Message = BTV_Constants.EmailExists;
                    }
                    ModelState.Clear();
                }
            }
            catch (Exception ex)
            {
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                ModelState.AddModelError("Error", BTV_Constants.ModelError);
            }

            var userId = (int)Session["user"];
            EditProfile userDetails = userAccount.GetuserDetailsAndLists(userId);
            return View(userDetails);
        }

        /// <summary>
        /// For User to Change Password
        /// </summary>
        [AuthenticateUser]
        public ActionResult ChangePassword()
        {
            EditProfile user = new EditProfile();

            var userId = (int)Session["user"];
            user.roleId = userAccount.GetRole(userId);
           // if (user.roleId == (int)UserRoles.Admin)
            //{
                return View(user);
            //}

            //return PartialView("_ChangePassword", user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(EditProfile user)
        {

BackToVillage/Views/UserAccount/ChangePassword.cshtml
@model BackToVillage.ViewModels.EditProfile

@{
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

@{
    ViewBag.Title = "Edit";

    if (Model.roleId == 1)
    {
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/UserLayout.cshtml";
    }

}
<label class="label label-success center-block" id="msg">@ViewBag.Message</label>
<h3 class="text-primary">Change Password</h3>
@using (Html.BeginForm("ChangePassword", "UserAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="form-horizontal" id="changePasswordDiv">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Set a Password", required = "required", id = "password" })
            </div>
            @Html.ValidationMessageFor(m => m.Password)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", placeholder = "Re-Enter Password", required = "required", id = "confirmPassword" })
            </div>
            @Html.ValidationMessageFor(m => m.ConfirmPassword, String.Empty, new { @class = "errorMessage" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

BackToVillage/Views/UserAccount/Edit.cshtml
@model BackToVillage.ViewModels.EditProfile

@{
    ViewBag.Title = "Edit";

    if (Model.roleId == 1)
    {
        Layout = "~/Views/Shared/AdminLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/UserLayout.cshtml";
    }

}
<h4>@ViewBag.Message</h4>
@using (Html.BeginForm("Edit", "UserAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3 class="text-primary">Edit Profile</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label", @required = "required" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your First Name", required = "required", id = "firstName", Value = Model.FirstName } })
            </div>
            @Html.ValidationMessageFor(m => m.FirstName, String.Empty, new { @class = "errorMessage" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", placeholder = "Enter your Last Name", required = "required", id = "lastName", Value = Model.LastName })
            </div>
            @Html.ValidationMessageFor(m => m.LastName, String.Empty, new { @class = "errorMessage" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.DOB, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.DOB, new
           {
               @class = "form-control", required = "required",
               id = "editedDob",
               Value = Model.DOB.ToShortDateString()
           })
            </div>
            @Html.ValidationMessageFor(m => m.DOB, String.Empty, new { @class = "errorMessage" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Enter your Email Id", required = "required", id = "email", type = "email", Value = Model.Email })
            </div>
            @Html.ValidationMessageFor(m => m.Email, String.Empty, new { @class = "errorMessage" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control", placeholder = "Enter your Phone Number", required = "required", id = "phone", Value = Model.PhoneNumber })
            </div>
            @Html.ValidationMessageFor(m => m.PhoneNumber, String.Empty, new { @class = "errorMessage" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.AltPhoneNumber, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.AltPhoneNumber, new { @class = "form-control", placeholder = "Enter your Alternate Phone Number", id = "altPhone", Value = Model.AltPhoneNumber })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.TextAreaFor(m => m.Address, new { @class = "form-control", placeholder = "Enter your Address", required = "required", id = "address", Value = Model.Address })
            </div>
            @Html.ValidationMessageFor(m => m.Address, String.Empty, new { @class = "errorMessage" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.OccupationList, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.DropDownListFor(model => model.SelectedOccupationId, new SelectList(Model.OccupationList, "OccupationId", "OccupationName"), "Select Occupation", new { @class = "form-control dropdown" })

            </div>
            @Html.ValidationMessageFor(m => m.SelectedOccupationId, String.Empty, new { @class = "errorMessage" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.StateList, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.DropDownListFor(model => model.SelectedStateId, new SelectList(Model.StateList, "StateId", "StateName"), "Select State", new { @class = "form-control dropdown", id = "stateList" })

            </div>
            @Html.ValidationMessageFor(m => m.SelectedStateId, String.Empty, new { @class = "errorMessage" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.CityList, new { @class = "col-md-2 control-label" })
            <div class="col-md-3">
                @Html.DropDownListFor(model => model.SelectedCityId, new SelectList(Enumerable.Empty<SelectListItem>(), "CityId", "CityName"), "Select City", new { @class = "form-control dropdown", id = "cityList", required = "required" })

            </div>
            @Html.ValidationMessageFor(m => m.SelectedCityId, String.Empty, new { @class = "errorMessage" })
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>

}

BackToVillage/Views/UserAccount/Login.cshtml
@model BackToVillage.ViewModels.LoginVm

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<label class="label label-success center-block" id="msg">@Html.ValidationMessage("Error")</label>
<label class="label label-success center-block" id="msg">@ViewBag.Message</label>
<div class="register loginDiv">
    <h1>Login</h1>
    @using (Html.BeginForm("Login", "UserAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <hr />

        <div>
            <div class="form-group" id="loginFormGroup">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "errorMessage" })
            </div>

            <div class="form-group" id="loginFormGroup">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                </div>
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "errorMessage" })
            </div>

            <div class="form-group" id="loginBtnFormGroup">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-primary" id="loginBtn" />
                </div>
            </div>
        </div>
    }

</div>

BackToVillage/Views/UserAccount/Register.cshtml
@model BackToVillage.ViewModels.UserDetails
@{
    ViewBag.Title = "Register Here";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Register.css" rel="stylesheet" />
<label class="label label-success center-block" id="msg">@Html.ValidationMessage("Error")</label>
<label class="label label-success center-block msg">@ViewBag.Message</label>

<div id="register" class="register">
    <h1>Register</h1>
    @using (Html.BeginForm("Register", "UserAccount", FormMethod.Post, htmlAttributes: new { id = "loginForm", @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <hr />

        <div>
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your First Name", required = "required", id = "firstName" } })
                </div>
                @Html.ValidationMessageFor(m => m.FirstName, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", placeholder = "Enter your Last Name", required = "required", id = "lastName" })
                </div>
                @Html.ValidationMessageFor(m => m.LastName, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.DOB, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.TextBoxFor(m => m.DOB, new { @class = "form-control", type = "date", required = "required", id = "dob", min = "1950-01-01" })
                </div>
                @Html.ValidationMessageFor(m => m.DOB, String.Empty, new { @class = "errorMessage" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Gender, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    <label class="radio-inline">
                        @Html.RadioButtonFor(m => m.Gender, "Male", new { @class = "user control_radio", id = "user_gender" })<span class="radio_label">Male</span>
                    </label>
                    <label class="radio-inline">
                        @Html.RadioButtonFor(m => m.Gender, "Female", new { @class = "user control_radio", id = "user_gender" })<span class="radio_label">Female</span>
                    </label>
                </div>
                @Html.ValidationMessageFor(m => m.Gender, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Enter your Email Id", required = "required", id = "email", type = "email" })
                </div>
                @Html.ValidationMessageFor(m => m.Email, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control", placeholder = "Enter your Phone Number", required = "required", id = "phone" })
                </div>
                @Html.ValidationMessageFor(m => m.PhoneNumber, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.AltPhoneNumber, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.TextBoxFor(m => m.AltPhoneNumber, new { @class = "form-control", placeholder = "Enter your Alternate Phone Number", id = "altPhone" })
                </div>

            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.TextAreaFor(m => m.Address, new { @class = "form-control", placeholder = "Enter your Address", required = "required", id = "address" })
                </div>
                @Html.ValidationMessageFor(m => m.Address, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.OccupationList, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.DropDownListFor(model => model.SelectedOccupationId, new SelectList(Model.OccupationList, "OccupationId", "OccupationName"), "Select Occupation", new { @class = "form-control dropdown" })

                </div>
                @Html.ValidationMessageFor(m => m.SelectedOccupationId, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.StateList, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.DropDownListFor(model => model.SelectedStateId, new SelectList(Model.StateList, "StateId", "StateName"), "Select State", new { @class = "form-control dropdown", id = "stateList" })

                </div>
                @Html.ValidationMessageFor(m => m.SelectedStateId, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.CityList, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.DropDownListFor(model => model.SelectedCityId, new SelectList(Enumerable.Empty<SelectListItem>(), "CityId", "CityName"), "Select City", new { @class = "form-control dropdown", id = "cityList" })

                </div>
                @Html.ValidationMessageFor(m => m.SelectedCityId, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Set a Password", required = "required", id = "password" })
                </div>
                @Html.ValidationMessageFor(m => m.Password, String.Empty, new { @class = "errorMessage" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label regdlabel" })
                <div class="col-md-3">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", placeholder = "Re-Enter Password", required = "required", id = "confirmPassword" })
                </div>
                @Html.ValidationMessageFor(m => m.ConfirmPassword, String.Empty, new { @class = "errorMessage" })
            </div>




            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="checkbox">
                        @Html.CheckBoxFor(m => m.isSelected)
                        @Html.LabelFor(m => m.isSelected, new { @class = "regdlabel" })
                    </div>
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-primary" value="Register" />
                </div>
            </div>
        </div>
    }

</div>